export const ACTION_TYPES = {
  SET_EMPLOYEE_LIST: "APP.SET_EMPLOYEE_LIST",
  SET_USER_MOBILE_NUMBER: "APP.SET_USER_MOBILE_NUMBER",
  SET_USER_DETAILS: "APP.SET_USER_DETAILS",
  SET_PROP_REMINDER_LIST: "APP.SET_PROP_REMINDER_LIST"
};
